{% set name = "rnabridge-denovo" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://github.com/Shao-Group/rnabridge-denovo/releases/download/v{{ version }}/rnabridge-denovo-{{ version }}.tar.gz"
  sha256: "d5dcdfbc87a879ce9ebf90d78fa92f3a69e1ddf8d99699bb9de9d6acc2b76fd9"

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bifrost
  run:
    - bifrost

test:
  commands:
    - rnabridge-denovo --help
    
about:
  home: "https://github.com/Shao-Group/rnabridge-denovo"
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "A tool to construct the alignments of entire fragments given the alignments of paired-end reads."

extra:
  recipe-maintainers:
    - shaogroup